Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace OdeToFood.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/Restraunts/ClientRestraunt.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OdeToFood.Pages.Restraunts
{
    public class ClientRestrauntModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/Restraunts/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restraunts
{
    public class DeleteModel : PageModel
    {
        private readonly IRestrauntData restrauntData;
       public Restraunt Restraunt { get; set; }
        public DeleteModel(IRestrauntData  restrauntData)
        {
            this.restrauntData = restrauntData;
        }
        public IActionResult OnGet(int id)
        {
            Restraunt = restrauntData.GetRestrauntById(id);
            if (Restraunt == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
        public IActionResult OnPost(int id)
        {
          var result =  restrauntData.Delete(id);
            restrauntData.Commit();
            if(result==null)
            {
                return RedirectToPage("./NotFound");
            }
            TempData["Message"] = $"{result.Name} with Id {result.Id} deleted !";
            return RedirectToPage("./List");
        }
    }
}

Pages/Restraunts/Detail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restraunts
{
    public class DetailModel : PageModel
    {
        private readonly IRestrauntData restrauntData;
        [TempData]
        public string Message { get; set; }
        public DetailModel(IRestrauntData restrauntData)
        {
            this.restrauntData = restrauntData;
        }
        public Restraunt restraunt { get; set; }
        public IActionResult OnGet(int id)
        {
            restraunt = restrauntData.GetRestrauntById(id);
            if (restraunt == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
    }
}

Pages/Restraunts/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restraunts
{
    public class EditModel : PageModel
    {
        private readonly IRestrauntData restrauntData;
        private readonly IHtmlHelper htmlHelper;
        [BindProperty]
        public Restraunt restraunt{ get; set; }
        public IEnumerable<SelectListItem> Cuisines { get; set; }
        public EditModel(IRestrauntData restrauntData,IHtmlHelper htmlHelper)
        {
            this.restrauntData = restrauntData;
            this.htmlHelper = htmlHelper;
        }
        public IActionResult OnGet(int? id)
        {

            Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
            if (id.HasValue)
            {
                restraunt = restrauntData.GetRestrauntById(id.Value);

            }
            else
            {
                restraunt = new Restraunt();
            }
            if (restraunt == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
        public IActionResult OnPost()
        {
            Cuisines = htmlHelper.GetEnumSelectList<CuisineType>();
            if (!ModelState.IsValid)
            {

                return Page();

                
            }
            if (restraunt.Id > 0)
            {
                this.restraunt = restrauntData.Update(restraunt);
                
            }
            else
            {
                this.restrauntData.Create(restraunt);
            }
            restrauntData.Commit();
            TempData["Message"] = "Successful operation";
            return RedirectToPage("./Detail", new { id = restraunt.Id });
        }
    }
}

Pages/Restraunts/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using OdeToFood.Core;
using OdeToFood.Data;

namespace OdeToFood.Pages.Restraurants
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration config;
        private readonly IRestrauntData restrauntData;
        [BindProperty(SupportsGet =true)]
        public string SearchRes { get; set; }
        public IEnumerable<Restraunt> Restraunts { get; set; }

        public string Message { get; set; }
        public ListModel(IRestrauntData restrauntData,IConfiguration configuration  )
        {
            this.restrauntData = restrauntData;
            this.config = configuration;
        }
       /* public void OnGet()
        {
          Restraunts=  restrauntData.GetAll();
        }*/
        public void OnGet(string searchRes=null)
        {
            Restraunts = restrauntData.GetRestrauntByName(searchRes);
        }
    }
}

Pages/ViewComponents/RestrauntCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OdeToFood.Pages.ViewComponents
{
    public class RestrauntCountViewComponent : ViewComponent
    {
        private readonly IRestrauntData restrauntData;

        public RestrauntCountViewComponent(IRestrauntData restrauntData)
        {
            this.restrauntData = restrauntData;
        }
        public IViewComponentResult Invoke()
        {
            var count = restrauntData.RestrauntsCount();
            return View(count);
        }
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Restraunts/ClientRestraunt.cshtml
@page
@model OdeToFood.Pages.Restraunts.ClientRestrauntModel
@{
    ViewData["Title"] = "ClientRestraunt";
}

<h1>ClientRestraunt</h1>
@section Scripts{ 
        <script>

            $(function () {

                $.ajax("/api/Restraunts/", { method: "get" }).
                    then(function (response) {
                    console.log(response);
                })
            });
        </script>
}

Pages/Restraunts/Delete.cshtml
@page "{id:int}"
@model OdeToFood.Pages.Restraunts.DeleteModel


    <h2>Delete !</h2>
    <div class="alert alert-danger" >Are you sure to Delete ?? @Model.Restraunt.Name </div>
    <form method="post">
        <button type="submit" class="btn btn-danger">Yes I'm Sure</button>
        <a asp-page="List" class="btn btn-group" >Cancel</a>
    </form>

Pages/Restraunts/Detail.cshtml
@page "{id:int}"
@model OdeToFood.Pages.Restraunts.DetailModel
@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>
<div>
    ID: @Model.restraunt.Id
</div>
<div>
    Name: @Model.restraunt.Name
</div>
<div>
    Location: @Model.restraunt.Location
</div>
<div>
    Cuisine Type: @Model.restraunt.Cuisine
</div>
@if(@Model.Message!=null){
     <div class="alert alert-info">@Model.Message</div>  
}

<a asp-page="./List" class="btn btn-dark">Back To All Restraunts</a>

Pages/Restraunts/Edit.cshtml
@page "{id:int?}"
@model OdeToFood.Pages.Restraunts.EditModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<form method="post">
    <input type="hidden" asp-for="restraunt.Id" />
    <div class="form-group">
        <label asp-for="restraunt.Name"></label>
        <input asp-for="restraunt.Name" class="form-control" />
        <span class="text-danger" asp-validation-for="restraunt.Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="restraunt.Location"></label>
        <input asp-for="restraunt.Location" class="form-control" />
        <span class="text-danger" asp-validation-for="restraunt.Location"></span>

    </div>
    <div class="form-group">
        <label asp-for="restraunt.Cuisine"></label>
        <select asp-for="restraunt.Cuisine" class="form-control"
                asp-items="Model.Cuisines"></select>
    </div>
    <button type="submit" class="btn btn-primary">Save</button>
</form>
@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

Pages/Restraunts/List.cshtml
@page
@model OdeToFood.Pages.Restraurants.ListModel
@{
    ViewData["Title"] = "List";
}

<h1>Restraunts</h1>
<form method="get">
    <div class="form-group">
        <div class="input-group">
            <input type="search" class="form-control" asp-for="SearchRes" />
            <span class="input-group-btn">
                <button class="btn btn-outline-light">
                    <i class="navbar-toggler-icon"></i>
                </button>
            </span>
        </div>

    </div>

</form>
@foreach(var restraunt in Model.Restraunts)
{

    <partial name="_Summary"model="restraunt"/>
}
<a asp-page="./Edit" class="btn btn-primary">Create New</a>

@section footer{
    <div> Hello From Footer</div>

}

Pages/Restraunts/NotFound.cshtml
@page
@{
    ViewData["Title"] = "NotFound";
}

<h1>Your restraunt is Not Found</h1>
<a class="btn btn-primary" asp-page="./List">Back to All Restraunts</a>

Pages/Restraunts/_Summary.cshtml
@using OdeToFood.Core
@model Restraunt 

<div >
    <h3>@Model.Name</h3>
    <div>Location : @Model.Location</div>
    <div>Cuisine : @Model.Cuisine</div>
    <div>

        <a asp-page="./Detail" asp-route-id="@Model.Id">Details</a>
        <a asp-page="./Edit" asp-route-id="@Model.Id">Edit</a>
        <a asp-page="./Delete" asp-route-id="@Model.Id">Delete</a>

    </div>

</div>

Pages/Shared/Components/RestrauntCount/Default.cshtml
@model int
<div class="p-1">
    There are @Model Restraunts here  <a asp-page="/Restraunts/List">See Them All!</a> 
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OdeToFood</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OdeToFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Restraunts/List">Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @RenderSection("footer",required:false)
            <vc:restraunt-count></vc:restraunt-count>
            &copy; 2020 - OdeToFood - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>